apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
        {{- template  "mychart.labels" .}}
        {{- template  "mychart.app" .}}
data:
  myvalue: "Hello World"
  {{- if and .Values.favorite.drink (eq .Values.favorite.drink "coffee") }}
  mug: true
  {{end}}
  {{$relname := .Release.Name}}
  {{- with .Values.favorite -}}
  drink: {{.drink | default "tea" | quote}}
  Release: {{$relname}}
  food: {{.food}}
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings}}
    - {{. | title | quote}}
    {{- end}}
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }}
  toppings: |-
     {{- range $index, $topping := .Values.pizzaToppings }}
     {{ $index }}: {{ $topping }}
     {{- end }}



